# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\000032go6ee\tmp\build\80754af9\rsync-recipes\distributed-2021.8.1-python_3.8-on-winbuilder, last modified Thu Sep  2 19:23:28 2021
# ------------------------------------------------

package:
  name: distributed
  version: 2021.8.1
source:
  sha256: c13ac10ecd9ee5f0ff67f5697149062d6e483f23a079918df1ab2e19b11fa77d
  url: https://pypi.io/packages/source/d/distributed/distributed-2021.8.1.tar.gz
build:
  entry_points:
    - dask-scheduler=distributed.cli.dask_scheduler:go
    - dask-ssh=distributed.cli.dask_ssh:go
    - dask-worker=distributed.cli.dask_worker:go
  number: '0'
  script: C:\\ci\\distributed_1630629392970\\_h_env\\python.exe -m pip install . --no-deps
    --ignore-installed --no-cache-dir -vvv
  string: py38haa95532_0
requirements:
  build: []
  host:
    - ca-certificates 2021.7.5 haa95532_1
    - certifi 2021.5.30 py38haa95532_0
    - openssl 1.1.1l h2bbff1b_0
    - pip 21.2.2 py38haa95532_0
    - python 3.8.11 h6244533_1
    - setuptools 52.0.0 py38haa95532_0
    - sqlite 3.36.0 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.0 pyhd3eb1b0_0
    - wincertstore 0.2 py38_0
  run:
    - click >=6.6
    - cloudpickle >=1.5.0
    - colorama
    - cytoolz >=0.8.2
    - dask-core 2021.8.1.*
    - jinja2
    - msgpack-python >=0.6.0
    - psutil >=5.0
    - python >=3.8,<3.9.0a0
    - pyyaml
    - setuptools
    - sortedcontainers !=2.0.0,!=2.0.1
    - tblib >=1.6.0
    - toolz >=0.8.2
    - tornado >=6.0.3
    - zict >=0.1.3
  run_constrained:
    - openssl !=1.1.1e
test:
  commands:
    - pip check
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help
  imports:
    - distributed
    - distributed.cli
    - distributed.comm
    - distributed.deploy
    - distributed.diagnostics
    - distributed.protocol
  requires:
    - pip
about:
  description: 'Distributed is a lightweight library for distributed computing in
    Python.

    It extends both the concurrent.futures and dask APIs to moderate sized

    clusters.

    '
  dev_url: https://github.com/dask/distributed
  doc_source_url: https://github.com/dask/distributed/blob/master/docs/source/index.rst
  doc_url: https://distributed.dask.org
  home: http://distributed.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Distributed computing with Dask
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jcrist
    - jrbourbeau
    - marcelotrevisani
    - martindurant
    - mrocklin
    - ogrisel
    - tomaugspurger
