# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\00002p0dqhh\tmp\build\80754af9\combined_recipe, last modified Wed Jul 14 04:56:26 2021
# ------------------------------------------------

package:
  name: cython
  version: 0.29.24
source:
  sha256: cdf04d07c3600860e8c2ebaad4e8f52ac3feb212453c1764a49ac08c827e8443
  url: https://pypi.io/packages/source/C/Cython/Cython-0.29.24.tar.gz
build:
  entry_points:
    - cygdb = Cython.Debugger.Cygdb:main
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main
  number: '0'
  script: C:\\ci\\cython_1626257071357\\_h_env\\python.exe -m pip install . --no-deps
    -vv
  string: py38hd77b12b_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2021.7.5 haa95532_1
    - certifi 2021.5.30 py38haa95532_0
    - openssl 1.1.1k h2bbff1b_0
    - pip 21.1.3 py38haa95532_0
    - python 3.8.10 hdbf39b2_7
    - setuptools 52.0.0 py38haa95532_0
    - sqlite 3.36.0 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.36.2 pyhd3eb1b0_0
    - wincertstore 0.2 py38_0
  run:
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - cython --version
  files:
    - fib.pyx
  imports:
    - Cython
    - Cython.Build
    - Cython.Build.Tests
    - Cython.Compiler
    - Cython.Compiler.Tests
    - Cython.Debugger
    - Cython.Debugger.Tests
    - Cython.Distutils
    - Cython.Plex
    - Cython.Runtime
    - Cython.Tempita
    - Cython.Tests
    - Cython.Utility
    - pyximport
  requires:
    - pip
    - vs2017_win-64
about:
  description: 'Cython is an optimising static compiler for both the Python programming

    language and the extended Cython programming language. It makes writing C

    extensions for Python as easy as Python itself.

    '
  dev_url: https://github.com/cython/cython
  doc_url: http://cython.org/#documentation
  home: http://www.cython.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: The Cython compiler for writing C extensions for the Python language
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - scopatz
    - synapticarbors
