# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\000035parta\tmp\build\80754af9\combined_recipe, last modified Mon Aug 16 11:53:37 2021
# ------------------------------------------------

package:
  name: bitarray
  version: 2.3.0
source:
  sha256: 21f2e10420f9ae74d3bdfd3cb74947ddbe9fbc0b2e5662f2f039001954f1d8b6
  url: https://pypi.io/packages/source/b/bitarray/bitarray-2.3.0.tar.gz
build:
  number: '1'
  script: C:\\ci\\bitarray_1629133092947\\_h_env\\python.exe -m pip install . --no-deps
    -vv
  string: py38h2bbff1b_1
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2021.7.5 haa95532_1
    - certifi 2021.5.30 py38haa95532_0
    - openssl 1.1.1k h2bbff1b_0
    - pip 21.2.2 py38haa95532_0
    - python 3.8.11 h6244533_1
    - setuptools 52.0.0 py38haa95532_0
    - sqlite 3.36.0 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.0 pyhd3eb1b0_0
    - wincertstore 0.2 py38_0
  run:
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  imports:
    - bitarray
  requires:
    - pip
about:
  description: 'Bitarray provides an object type which efficiently represents an array
    of

    booleans. Bitarrays are sequence types that behave very similarly

    to usual lists. All functionality is implemented in C.

    '
  dev_url: https://github.com/ilanschnell/bitarray
  doc_source_url: https://github.com/ilanschnell/bitarray/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/bitarray/0.8.1
  home: https://github.com/ilanschnell/bitarray
  license: PSF
  license_family: PSF
  license_file: LICENSE
  summary: efficient arrays of booleans -- C extension
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - nehaljwani
