# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\0000223u74c\tmp\build\80754af9\rsync-recipes\debugpy-1.4.1-python_3.8-on-winbuilder, last modified Tue Aug 17 11:40:11 2021
# ------------------------------------------------

package:
  name: debugpy
  version: 1.4.1
source:
  sha256: 889316de0b8ff3732927cb058cfbd3371e4cd0002ecc170d34c755ad289c867c
  url: https://pypi.io/packages/source/d/debugpy/debugpy-1.4.1.zip
build:
  number: '0'
  string: py38hd77b12b_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2021.7.5 haa95532_1
    - certifi 2021.5.30 py38haa95532_0
    - openssl 1.1.1k h2bbff1b_0
    - pip 21.2.2 py38haa95532_0
    - python 3.8.11 h6244533_1
    - setuptools 52.0.0 py38haa95532_0
    - sqlite 3.36.0 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.0 pyhd3eb1b0_0
    - wincertstore 0.2 py38_0
  run:
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  imports:
    - debugpy
    - debugpy.adapter
    - debugpy.common
    - debugpy.launcher
    - debugpy.server
  requires:
    - pip
about:
  dev_url: https://github.com/microsoft/debugpy
  home: https://github.com/Microsoft/debugpy
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyNotices.txt
  summary: An implementation of the Debug Adapter Protocol for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jtilly
    - xhochy
