# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Fri Feb 26 18:03:25 2021
# ------------------------------------------------

package:
  name: dataclasses
  version: '0.8'
source:
  sha256: 8479067f342acf957dc82ec415d355ab5edb7e7646b90dc6e2fd1d96ad084c97
  url: https://pypi.io/packages/source/d/dataclasses/dataclasses-0.8.tar.gz
build:
  noarch: python
  number: '7'
  script: /tmp/build/80754af9/dataclasses_1614362636673/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    --version
  string: pyh6d0b6a4_7
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - ca-certificates 2021.1.19 h06a4308_0
    - certifi 2020.12.5 py39h06a4308_0
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libedit 3.1.20191231 h14c3975_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1j h27cfd23_0
    - pip 21.0.1 py39h06a4308_0
    - python 3.9.1 hdb3f193_2
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py39h06a4308_0
    - sqlite 3.33.0 h62c20be_0
    - tk 8.6.10 hbc83047_0
    - tzdata 2020f h52ac0ba_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - python >=3.7
test:
  imports:
    - dataclasses
about:
  home: https://github.com/ericvsmith/dataclasses
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'An implementation of PEP 557: Data Classes'
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
