# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# C:\ci\containers\00003vfggrl\tmp\build\80754af9\combined_recipe, last modified Mon Sep 28 16:56:59 2020
# ------------------------------------------------

package:
    name: cfitsio
    version: '3.470'
source:
    patches:
        - lcurl-pkg-config.patch
        - ldflags.patch
        - unvendor_zlib.patch
    sha256: 985606e058403c073a68d95be74e9696f0ded9414520784457a1d4cba8cca7e2
    url: https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.47.tar.gz
build:
    number: '6'
    run_exports:
        - cfitsio >=3.470,<3.471.0a0
    string: he774522_6
requirements:
    build:
        - bzip2 1.0.8 he774522_0
        - cmake 3.18.2 hab937c2_0
        - libuv 1.40.0 he774522_0
        - lz4-c 1.9.2 h62dcd97_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
        - xz 5.2.5 h62dcd97_0
        - zlib 1.2.11 h62dcd97_4
        - zstd 1.4.5 h04227a9_0
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - if not exist %LIBRARY_LIB%\cfitsio.lib exit 1
        - if not exist %LIBRARY_BIN%\cfitsio.dll exit 1
about:
    description: 'CFITSIO is a library of C and Fortran subroutines for reading and
        writing

        data files in FITS (Flexible Image Transport System) data format. CFITSIO

        provides simple high-level routines for reading and writing FITS files that

        insulate the programmer from the internal complexities of the FITS format.

        CFITSIO also provides many advanced features for manipulating and filtering

        the information in FITS files.

        '
    doc_url: https://heasarc.gsfc.nasa.gov/docs/software/fitsio/quick/quick.html
    home: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
    license: fitsio
    license_file: License.txt
    summary: A library for reading and writing FITS files
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pkgw
        - teake
