# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Mon Jul 12 10:27:17 2021
# ------------------------------------------------

package:
  name: anaconda-project
  version: 0.10.1
source:
  sha256: 2e26f358bcfcd957a801980a1ab2cb71891214abf94e258330e205a2da0f50b3
  url: https://github.com/Anaconda-Platform/anaconda-project/archive/v0.10.1.tar.gz
build:
  entry_points:
    - anaconda-project = anaconda_project.cli:main
  noarch: python
  number: '0'
  script: /tmp/build/80754af9/anaconda-project_1626085644852/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . -vv --no-deps
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.7.5 h06a4308_1
    - certifi 2021.5.30 py39h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - pip 21.1.3 py39h06a4308_0
    - python 3.9.5 h12debd9_4
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py39h06a4308_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.10 hbc83047_0
    - tzdata 2021a h52ac0ba_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - anaconda-client
    - conda-pack
    - jinja2
    - python >=2.7
    - requests
    - ruamel_yaml
    - tornado >=4.2
    - tqdm
test:
  commands:
    - echo "First of test commands"
    - anaconda-project --help
    - anaconda-project --version
    - echo "Last of test commands"
  imports:
    - anaconda_project
about:
  description: 'By adding an anaconda-project.yml to a project directory, a single

    anaconda-project runcommand will be able to set up all dependencies

    and then launch the project.

    '
  dev_url: https://github.com/Anaconda-Platform/anaconda-project
  doc_url: http://anaconda-project.readthedocs.io
  home: https://github.com/Anaconda-Platform/anaconda-project
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Tool for encapsulating, running, and reproducing data science projects
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bollwyvl
    - fpliger
    - goanpeca
    - mingwandroid
