# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: curl
  version: 7.78.0
source:
  sha256: 98530b317dc95ccb324bbe4f834f07bb642fbc393b794ddf3434f246a71ea44a
  url: http://curl.haxx.se/download/curl-7.78.0.tar.bz2
build:
  noarch: false
  noarch_python: false
  number: '0'
  string: h86230a5_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2021.7.5 haa95532_1
    - krb5 1.19.2 h5b6d351_0
    - libcurl 7.78.0 h86230a5_0
    - libssh2 1.9.0 h7a1dbc1_1
    - openssl 1.1.1k h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - zlib 1.2.11 h62dcd97_4
  run:
    - krb5 >=1.19.2,<1.20.0a0
    - libcurl 7.78.0 h86230a5_0
    - libssh2 >=1.9.0,<2.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - curl --help
    - curl https://raw.githubusercontent.com/conda-forge/curl-feedstock/master/LICENSE.txt
    - if not exist %LIBRARY_BIN%\curl.exe exit 1
about:
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  dev_url: https://github.com/curl/curl
  doc_source_url: https://github.com/curl/curl/tree/master/docs
  doc_url: https://curl.haxx.se/docs/
  home: http://curl.haxx.se/
  license: curl
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
