# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\00002luvimb\tmp\build\80754af9\rsync-recipes\astropy-4.3.1-python_3.8-on-winbuilder, last modified Tue Aug 24 13:09:02 2021
# ------------------------------------------------

package:
  name: astropy
  version: 4.3.1
source:
  sha256: 2d3951223b4eb7f368fcad8c8340d27374c5d8e3b635a636275acdb38f35cd51
  url: https://pypi.io/packages/source/a/astropy/astropy-4.3.1.tar.gz
build:
  detect_binary_files_with_prefix: false
  entry_points:
    - fits2bitmap = astropy.visualization.scripts.fits2bitmap:main
    - fitscheck = astropy.io.fits.scripts.fitscheck:main
    - fitsdiff = astropy.io.fits.scripts.fitsdiff:main
    - fitsheader = astropy.io.fits.scripts.fitsheader:main
    - fitsinfo = astropy.io.fits.scripts.fitsinfo:main
    - samp_hub = astropy.samp.hub_script:hub_script
    - showtable = astropy.table.scripts.showtable:main
    - volint = astropy.io.votable.volint:main
    - wcslint = astropy.wcs.wcslint:main
  number: '0'
  script: C:\\ci\\astropy_1629829351783\\_h_env\\python.exe -m pip install . -vv
  string: py38hc7d831d_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - blas 1.0 mkl
    - brotli 1.0.9 ha925a31_2
    - ca-certificates 2021.7.5 haa95532_1
    - certifi 2021.5.30 py38haa95532_0
    - cycler 0.10.0 py38_0
    - cython 0.29.22 py38hd77b12b_0
    - extension-helpers 0.1 pyhd3eb1b0_0
    - fonttools 4.25.0 pyhd3eb1b0_0
    - freetype 2.10.4 hd328e21_0
    - icc_rt 2019.0.0 h0cc432a_1
    - icu 58.2 ha925a31_3
    - intel-openmp 2021.3.0 haa95532_3372
    - jinja2 2.10.3 py_0
    - jpeg 9b hb83a4c4_2
    - kiwisolver 1.3.1 py38hd77b12b_0
    - libpng 1.6.37 h2a8f88b_0
    - libtiff 4.2.0 hd0e1b90_0
    - lz4-c 1.9.3 h2bbff1b_1
    - markupsafe 2.0.1 py38h2bbff1b_0
    - matplotlib 3.4.2 py38haa95532_0
    - matplotlib-base 3.4.2 py38h49ac443_0
    - mkl 2020.2 256
    - mkl-service 2.3.0 py38h196d8e1_0
    - mkl_fft 1.3.0 py38h46781fe_0
    - mkl_random 1.1.1 py38h47e9c7a_0
    - munkres 1.1.4 py_0
    - numpy 1.19.2 py38hadc3359_0
    - numpy-base 1.19.2 py38ha3acd2a_0
    - olefile 0.46 py_0
    - openssl 1.1.1k h2bbff1b_0
    - pillow 8.3.1 py38h4fa10fc_0
    - pip 21.2.2 py38haa95532_0
    - pyparsing 2.4.7 pyhd3eb1b0_0
    - pyqt 5.9.2 py38ha925a31_4
    - python 3.8.11 h6244533_1
    - python-dateutil 2.8.2 pyhd3eb1b0_0
    - pyyaml 5.4.1 py38h2bbff1b_1
    - qt 5.9.7 vc14h73c81de_0
    - scipy 1.6.2 py38h14eb087_0
    - setuptools 52.0.0 py38haa95532_0
    - setuptools-scm 6.0.1 pyhd3eb1b0_1
    - setuptools_scm 6.0.1 hd3eb1b0_1
    - sip 4.19.13 py38ha925a31_0
    - six 1.16.0 pyhd3eb1b0_0
    - sqlite 3.36.0 h2bbff1b_0
    - tk 8.6.10 he774522_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tornado 6.1 py38h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.0 pyhd3eb1b0_0
    - wincertstore 0.2 py38_0
    - xz 5.2.5 h62dcd97_0
    - yaml 0.2.5 he774522_0
    - zlib 1.2.11 h62dcd97_4
    - zstd 1.4.9 h19a0ad4_0
  run:
    - matplotlib >=3.0,!=3.4.0
    - numpy >=1.19.2,<2.0a0
    - pyerfa >=1.7.3
    - python >=3.8,<3.9.0a0
    - pyyaml >=3.13
    - scipy >=1.2
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - fits2bitmap --help
    - fitscheck --help
    - fitsdiff --help
    - fitsheader --help
    - fitsinfo --help
    - samp_hub --help
    - volint --help
    - wcslint --help
    - showtable --help
  imports:
    - astropy
  requires:
    - pip
    - pytest-astropy >=0.8
    - setuptools
about:
  description: 'The Astropy Project is a community effort to develop a single package
    for

    Astronomy in Python. It contains core functionality and common tools

    needed for performing astronomy and astrophysics research with Python.

    '
  dev_url: https://github.com/astropy/astropy
  doc_url: http://docs.astropy.org/en/stable/
  home: http://www.astropy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Community-developed Python Library for Astronomy
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - astrofrog-conda-forge
    - bsipocz
    - mwcraig
