ignore_build_only_deps:
- numpy
- python
extend_keys:
- ignore_version
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libboost:
    max_pin: x.x.x
libffi:
- 3.2.1
blas_impl:
- mkl
boost_cpp:
- '1.73'
libxslt:
- '1.1'
pixman:
- '0.30'
tk:
- '8.6'
gstreamer:
- '1.14'
fontconfig:
- '2.13'
g2clib:
- '1.6'
lzo:
- '2'
libtiff:
- '4.1'
libgsasl:
- '1.8'
proj4:
- 5.2.0
fortran_compiler:
- intel-fortran
hdfeos5:
- '5.1'
cudatoolkit:
- '9.0'
libgd:
- 2.2.5
apr:
- 1.6.3
m2w64_cxx_compiler:
- m2w64-toolchain
libgdal:
- '3.0'
zlib:
- '1.2'
rust_compiler:
- rust-gnu
- rust
sqlite:
- '3'
libprotobuf:
- 3.11.2
freetype:
- '2.10'
xz:
- '5'
python_impl:
- cpython
bzip2:
- '1.0'
gst_plugins_base:
- '1.14'
serf:
- 1.3.9
expat:
- '2.2'
jpeg:
- '9'
libpng:
- '1.6'
llvm_variant:
- llvm
mkl:
- '2021'
hdf4:
- '4.2'
VERBOSE_AT:
- V=1
gnu:
- 2.12.2
openblas:
- 0.3.3
cross_compiler_target_platform:
- win-32
- win-64
perl:
- '5.26'
openjpeg:
- '2.3'
cairo:
- '1.14'
boost:
- '1.73'
lua:
- '5'
libkml:
- '1.3'
cyrus_sasl:
- 2.1.26
rust_compiler_version:
- 1.46.0
m2w64_fortran_compiler:
- m2w64-toolchain
giflib:
- '5'
openssl:
- 1.1.1
target_platform:
- win-64
python_implementation:
- cpython
gmp:
- '6.1'
harfbuzz:
- '2.4'
glib:
- '2'
qtwebkit:
- 'true'
m2w64_c_compiler:
- m2w64-toolchain
libnetcdf:
- '4.6'
cran_mirror:
- https://mran.microsoft.com/snapshot/2018-01-01
icu:
- '58'
VERBOSE_CM:
- VERBOSE=1
proj:
- 6.2.1
noarch_python:
- python
cpu_optimization_target:
- nocona
libdap4:
- '3.19'
dbus:
- '1'
mpfr:
- '4'
hdf5:
- 1.10.6
numpy:
- '1.16'
r_implementation:
- r-base
- mro-base
libwebp:
- 1.0.0
r_base:
- '3.5'
hdfeos2:
- '2.20'
r_version:
- 3.5.0
channel_targets:
- defaults
readline:
- '8.0'
libxml2:
- '2.9'
clang_variant:
- clang
c_compiler:
- vs2017
- vs2017
- vs2017
- vs2017
python:
- '3.8'
- '3.7'
- '3.6'
- '3.9'
cxx_compiler:
- vs2017
- vs2017
- vs2017
- vs2017
geos:
- 3.8.0
- 3.8.0
- 3.8.0
- 3.8.0
vc:
- '14'
- '14'
- '14'
- '14'
fortran_compiler_version:
- 2019.0.0
- 2019.0.0
- 2019.0.0
- 2019.0.0
zip_keys:
- - vc
  - c_compiler
  - cxx_compiler
  - fortran_compiler_version
  - python
  - geos
