# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Thu May 13 02:03:09 2021
# ------------------------------------------------

package:
  name: babel
  version: 2.9.1
source:
  fn: Babel-2.9.1.tar.gz
  sha256: bc0c176f9f6a994582230df350aa6e05ba2ebe4b3ac317eab29d9be5d2768da0
  url: https://pypi.io/packages/source/B/Babel/Babel-2.9.1.tar.gz
build:
  entry_points:
    - pybabel = babel.messages.frontend:main
  noarch: python
  number: '0'
  script: /tmp/build/80754af9/babel_1620871417480/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - ca-certificates 2021.4.13 h06a4308_1
    - certifi 2020.12.5 py39h06a4308_0
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - pip 21.0.1 py39h06a4308_0
    - python 3.9.4 hdb3f193_0
    - pytz 2021.1 pyhd3eb1b0_0
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py39h06a4308_0
    - sqlite 3.35.4 hdfb4753_0
    - tk 8.6.10 hbc83047_0
    - tzdata 2020f h52ac0ba_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - python >=3.6
    - pytz >=2015.7
test:
  commands:
    - pybabel --help
  imports:
    - babel
    - babel.localtime
    - babel.messages
about:
  description: 'Babel is an integrated collection of utilities that assist in

    internationalizing and localizing Python applications, with an emphasis

    on web-base applications.

    '
  dev_url: https://github.com/python-babel/babel
  doc_source_url: https://github.com/python-babel/babel/blob/master/docs/index.rst
  doc_url: http://babel.pocoo.org/en/latest/#user-documentation
  home: http://babel.pocoo.org/
  license: BSD 3-clause
  license_file: LICENSE
  summary: Utilities to internationalize and localize Python applications
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - frol
    - nehaljwani
