# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/beautifulsoup4-4.10.0-on-linux_64, last modified Fri Sep 17 10:36:24 2021
# ------------------------------------------------

package:
  name: beautifulsoup4
  version: 4.10.0
source:
  sha256: c23ad23c521d818955a4151a67d81580319d4bf548d3d49f4223ae041ff98891
  url: https://pypi.io/packages/source/b/beautifulsoup4/beautifulsoup4-4.10.0.tar.gz
build:
  noarch: python
  number: '0'
  string: pyh06a4308_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.7.5 h06a4308_1
    - certifi 2021.5.30 py39h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.4 py37h06a4308_0
    - python 3.9.7 h12debd9_1
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py39h06a4308_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.10 hbc83047_0
    - tzdata 2021a h5d7bf9c_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - python >=3.6
    - soupsieve >=1.2
about:
  description: 'Beautiful Soup is a library for pulling data out of HTML and XML files.

    It provides ways of navigating, searching, and modifying parse trees.

    '
  dev_url: https://code.launchpad.net/beautifulsoup
  doc_source_url: https://github.com/newvem/beautifulsoup4/blob/master/doc/source/index.rst
  doc_url: http://beautiful-soup-4.readthedocs.io/en/latest/
  home: http://www.crummy.com/software/BeautifulSoup/
  license: MIT
  license_family: MIT
  license_file: COPYING.txt
  summary: Python library designed for screen-scraping
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jschueller
    - nehaljwani
