# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/appdirs-feedstock/recipe, last modified Sat Aug  7 09:28:24 2021
# ------------------------------------------------

package:
  name: appdirs
  version: 1.4.4
source:
  sha256: 7d5d0167b2b1ba821647616af46a749d1c653740dd0d2415100fe26e27afdf41
  url: https://pypi.io/packages/source/a/appdirs/appdirs-1.4.4.tar.gz
build:
  noarch: python
  number: '0'
  script: python setup.py install --single-version-externally-managed --record record.txt
  string: pyhd3eb1b0_0
requirements:
  host:
    - ca-certificates 2021.7.5 hca03da5_1
    - certifi 2021.5.30 py39hca03da5_0
    - expat 2.4.1 hc377ac9_2
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.3 hc4ed4cf_2
    - libiconv 1.16 h1230e6a_0
    - ncurses 6.2 hc4ed4cf_0
    - openssl 1.1.1j h1230e6a_0
    - pip 21.2.3 py39hca03da5_0
    - python 3.9.6 hc70090a_5
    - readline 8.1 h1230e6a_0
    - setuptools 52.0.0 py39hca03da5_0
    - sqlite 3.36.0 h1058600_0
    - tk 8.6.10 h6b60437_0
    - tzdata 2021a h5d7bf9c_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 hca03da5_3
  run:
    - python
test:
  imports:
    - appdirs
about:
  home: http://github.com/ActiveState/appdirs
  license: MIT
  license_file: LICENSE.txt
  summary: A small Python module for determining appropriate platform-specific dirs.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
